FROM ubuntu
LABEL description="this image is rapsberry pi ubuntu cross compilation environment, which installed necessary tool chain. Also with build azure iot sdks c."

#those packages are necessary for building azure iot sdk
RUN apt-get update
RUN apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    libcurl4-openssl-dev \
    libssl-dev \
    make \
    pkg-config \
    sshpass \
    uuid-dev \
    valgrind \
    sshpass

#RUN sh -c "echo 'deb http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid main' >> /etc/apt/sources.list"
#RUN sh -c "echo 'deb-src http://ppa.launchpad.net/aziotsdklinux/ppa-azureiot/ubuntu vivid main' >> /etc/apt/sources.list"
#RUN apt-key adv --keyserver keyserver.ubuntu.com --recv-keys FDA6A393E4C2257F
#RUN apt-get install -y azure-iot-sdk-c-dev
 
RUN git clone https://github.com/yungez/rpitools.git
RUN git clone --recursive https://github.com/Azure/azure-iot-sdk-c.git

ENV RPI_ROOT ${PWD}/rpitools/raspbian-jessie-sysroot

RUN PATH=$PATH:./rpitools/arm-linux-gnueabihf/bin

# copy build script
COPY toolchain-raspberrypi.cmake /home
COPY index.sh /index.sh
COPY deploy.sh /deploy.sh
COPY build_raspberrypi.sh /build.sh

# build azure iot sdks

RUN ./azure-iot-sdk-c/build_all/linux/build.sh --toolchain-file /home/toolchain-raspberrypi.cmake -cl --sysroot=$RPI_ROOT

RUN echo 'alias gcc="arm-linux-gnueabihf-gcc --sysroot=$RPI_ROOT"' >> ~/.bashrc

ENV CC ${PWD}/rpitools/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc
ENV CXX ${PWD}/rpitools/arm-linux-gnueabihf/bin/arm-linux-gnueabihf-g++

RUN echo clone iot-hub-c-raspberrypi-getting-started
RUN git clone -b develop --recursive https://github.com/Azure-samples/iot-hub-c-raspberrypi-getting-started.git
RUN echo build iot-hub-c-raspberrypi-getting-started
RUN cd iot-hub-c-raspberrypi-getting-started/ && cmake -DCMAKE_TOOLCHAIN_FILE=/home/toolchain-raspberrypi.cmake -DcompileOption_C:STRING="--sysroot=$RPI_ROOT" -Dazure_IoT_Sdk_c=/azure-iot-sdk-c . && make