FROM ubuntu:latest
LABEL description="this image is intel edison ubuntu cross compilation environment, which installed necessary tool chain. Also with build azure iot sdks c."

#those packages are necessary for building azure iot sdk
RUN apt-get clean && apt-get update
RUN apt-get install -y \
    build-essential \
    cmake \
    curl \
    git \
    libcurl4-openssl-dev \
    libssl-dev \
    make \
    pkg-config \
    sshpass \
    uuid-dev \
    valgrind \
	wget \
	unzip \
    python

RUN wget http://downloadmirror.intel.com/25028/eng/edison-sdk-linux64-ww25.5-15.zip && unzip -o edison-sdk-linux64-ww25.5-15.zip && ./poky-edison-glibc-x86_64-edison-image-core2-32-toolchain-1.7.2.sh -d /edison-sdk -y && rm edison-sdk-linux64-ww25.5-15.zip poky-edison-glibc-x86_64-edison-image-core2-32-toolchain-1.7.2.sh

ENV SYSROOT=/edison-sdk/sysroots/core2-32-poky-linux
ENV CC=/edison-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux/i586-poky-linux-gcc
ENV CXX=/edison-sdk/sysroots/x86_64-pokysdk-linux/usr/bin/i586-poky-linux/i586-poky-linux-g++

COPY toolchain.cmake /home

# build azure iot sdks
RUN git clone --recursive https://github.com/Azure/azure-iot-sdk-c.git
RUN /azure-iot-sdk-c/build_all/linux/build.sh --toolchain-file /home/toolchain.cmake -cl --sysroot=$SYSROOT
ENV AZURE_IOT_SDK /azure-iot-sdk-c

COPY index.sh /index.sh
COPY deploy.sh /deploy.sh
COPY build.sh /build.sh