SET(CMAKE_SYSTEM_NAME Linux)     # this one is important
SET(CMAKE_SYSTEM_VERSION 1)     # this one not so much
SET(CMAKE_C_COMPILER $ENV{RPI_ROOT}/../arm-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc)
SET(CMAKE_SYSROOT $ENV{RPI_ROOT})
SET(CMAKE_FIND_ROOT_PATH $ENV{RPI_ROOT})
SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)